### ISSUE TITLE
Missing option to download built binary

### ISSUE THREAD

**Issue by crazyscientist** [crazyscientist/osc-tiny#74]
### Description

* `Build.get_binary` is named misleading: Instead of getting a binary, this method returns the content of the file as decoded string.
* The extension is not addressing the use case for downloading binaries.

### Tasks

* [ ] Change the method's docstring to clarify it's use case
* [ ] Add a parameter to method to return raw binary string
* [ ] Add a method to download the binary to a file

@marcosps, thank you for pinging me about this

**Comment by marcosps** [comment]
@crazyscientist this PR implements the first two tasks of the issue. Right now it works as expected. For my use case, it fixed the problem. I can implement the method to download to a file later if it's required.
